export const routes = {
    client: {
        main: '/',
        news: '/news',
        news_id: '/news/:newsId',
        partner: '/partners',
        project: '/projects',
        project_id: '/projects/:projectId',
        researches: '/researches',
        researches_id: '/researches/:researchesId',
        company_history: '/history',
        team: '/team',
        reporting: '/reporting',
        contacts: '/contacts',
        search: '/search',
    },
    admin: {
        dashboard: '/dashboard',
        news: '/dashboard/news',
        news_id: '/dashboard/news/:newsId',
        partner: '/dashboard/partners',
        partner_id: '/dashboard/partners/:partnersId',
        project: '/dashboard/project',
        project_id: '/dashboard/project/:projectId',
        researches: '/dashboard/researches',
        researches_id: '/dashboard/researches/:researchesId',
        reporting: '/dashboard/reporting',
    },
    login: '/login',
};
