export const routes = {
    client: {
        main: '/',
        news: '/news',
        news_id: '/news/:newsId',
        partner: '/partners',
        project: '/projects',
        project_id: '/projects/:projectId',
        discover: '/discover',
        discover_id: '/discover/:discoverId',
        company_history: '/history',
        team: '/team',
        team_id: '/team/:teamId',
        reporting: '/reporting',
        contacts: '/contacts',
        search: '/search',
    },
    admin: {
        dashboard: '/dashboard',
        news: '/dashboard/news',
        news_create: '/dashboard/news/create',
        news_id: '/dashboard/news/:newsId',
        partner: '/dashboard/partners',
        partner_id: '/dashboard/partners/:partnersId',
        project: '/dashboard/project',
        project_id: '/dashboard/project/:projectId',
        discover: '/dashboard/discover',
        discover_id: '/dashboard/discover/:discoverId',
        reporting: '/dashboard/reporting',
        incoming: '/dashboard/incoming',
    },
    login: '/login',
};
