import { createBrowserRouter } from 'react-router-dom';

import { routes } from '@/constants';
import {
    Contacts,
    HomePage,
    NewsById,
    NewsPage,
    TeamPage,
    AdminNews,
    Dashboard,
    ErrorPage,
    LoginPage,
    TeamsById,
    SearchPage,
    AdminNewsId,
    HistoryPage,
    ProjectById,
    ProjectPage,
    AdminProject,
    DiscoverById,
    DiscoverPage,
    LayoutClient,
    PartnersPage,
    IncomingPage,
    ReportingPage,
    AdminPartnerId,
    NewsCreatePage,
    LayoutDashboard,
    IncomingByIdPage,
    AdminPartnersPage,
    PartnersCreatePage,
    AdminReportingPage,
} from '@/pages';

const { client, admin, login } = routes;

export const router = createBrowserRouter([
    {
        path: '/',
        element: <LayoutClient />,
        errorElement: <ErrorPage />,
        children: [
            { index: true, element: <HomePage /> },
            { path: client.news, element: <NewsPage /> },
            { path: client.news_id, element: <NewsById /> },
            { path: client.partner, element: <PartnersPage /> },
            { path: client.project, element: <ProjectPage /> },
            { path: client.project_id, element: <ProjectById /> },
            { path: client.discover, element: <DiscoverPage /> },
            { path: client.discover_id, element: <DiscoverById /> },
            { path: client.company_history, element: <HistoryPage /> },
            { path: client.team, element: <TeamPage /> },
            { path: client.team_id, element: <TeamsById /> },
            { path: client.reporting, element: <ReportingPage /> },
            { path: client.contacts, element: <Contacts /> },
            { path: client.search, element: <SearchPage /> },
        ],
    },
    {
        path: login,
        element: <LoginPage />,
    },
    {
        path: admin.dashboard,
        element: <LayoutDashboard />,
        children: [
            { index: true, element: <Dashboard /> },
            { path: admin.news, element: <AdminNews /> },
            { path: admin.news_id, element: <AdminNewsId /> },
            { path: admin.news_create, element: <NewsCreatePage /> },
            { path: admin.partner, element: <AdminPartnersPage /> },
            { path: admin.partner_create, element: <PartnersCreatePage /> },
            { path: admin.partner_id, element: <AdminPartnerId /> },
            { path: admin.project, element: <AdminProject /> },
            { path: admin.project_id, element: <h1>admin project_id</h1> },
            { path: admin.discover, element: <h1>admin discover</h1> },
            { path: admin.discover_id, element: <h1>admin discover_id</h1> },
            { path: admin.reporting, element: <AdminReportingPage /> },
            { path: admin.incoming, element: <IncomingPage /> },
            { path: admin.incoming_id, element: <IncomingByIdPage /> },
        ],
    },
]);
